REDIS_EVENT_PATH_KEY = b"file_path"
REDIS_EVENT_TYPE_KEY = b"action"
REDIS_GROUP_ALREADY_CREATED = "BUSYGROUP"

INOTIFY_FINISHED_WRITE_EVENT = "CLOSE_WRITE"
INOTIFY_CREATE_EVENT = "CREATE"
INOTIFY_DELETE_EVENT = "DELETE"
